@startuml
'https://plantuml.com/sequence-diagram

class Tarjeta {
    -double saldo
    -Central centralEmisora
    +Tarjeta(Central CE)
    +double obtenerSaldo()
    +void recargar(double saldo)
    +void viajar()
    -boolean puedoViajar()
}

class Central {
    -double costoViaje
    +Central(double costoViaje)
    +void cambiarPrecio(double precio)
    +double obtenerPrecio()
}

Tarjeta *-- Central

@enduml