@startuml
'https://plantuml.com/class-diagram

class ComplexNumber{
    -double realPart
    -double imaginaryPart
    +ComplexNumber(double real, double imag)
    +ComplexNumber(double real)
    +double getReal()
    +double getImaginary()
    +ComplexNumber sum(ComplexNumber n)
}
@enduml