@startuml
'https://plantuml.com/sequence-diagram

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|- AbstractCollection

Collection <|- List
AbstractList <|-- AbstractCollection
AbstractList <|-- ArrayList

class ArrayList {
    Object[] elementData
    int day
    int month
    int year
    size()
}
enum TimeUnits {
 DAYS
 HOURS
 MINUTES
}
@enduml