@startuml
'https://plantuml.com/class-diagram

class Affiliate {
    -String firstName
    -String lastName
    -int affiliateNumber
    -static int lastNumber
    -Date birthDate
    +Affiliate(String firstName, String lastName, Date birth)
    -static int getAndIncrement()
    +String getLastName()
    +String getFirstName()
    +Date getBirthDate()
}

@enduml