@startuml
'https://plantuml.com/sequence-diagram

class Counter {
    -int count
    +Counter()
    +int getCount()
    +void incCount()
    +void decCount()
}

class MultipleCounter {
    -private int times
    +public MultipleCounter(int times)
    +void incCount()
    +void decCount()
}

Counter <|-- MultipleCounter

@enduml